# -*- coding: utf-8 -*-
"""exercicio_calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/198FJe2m1wDt5gxF3P2MsaKwF_G360xcO

#Calculadora
"""

nome = input("Digite seu nome: ")
print("Olá", nome, "seja bem vindo/a!")
print(nome, "vamos utilizar a calculadora!")

num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número:" ))

print(nome, "Abaixo está os resultados calculados!")
print("Soma: ", num1 + num2)
print("Subtração: ", num1 - num2)
print("Multiplicação: ", num1 * num2)
print("Divisão: ", num1 / num2)
if num1 > num2:
  print("O maior número digitado é: ", num1)
elif num2 > num1:
  print("O maior número digitado é: ", num2)
else:
  print("Os números são iguais!")